-- ====================================================================================
-- SQL Management Templates for `elt_pipeline_configs`
--
-- Use these templates to add, update, or remove pipeline configurations.
-- ====================================================================================


-- ====================================================================================
-- TEMPLATE 1: INSERT a new pipeline configuration
--
-- Instructions:
-- 1. Uncomment the INSERT statement below.
-- 2. Fill in the values for your new pipeline.
-- 3. Pay close attention to the comments explaining each field.
-- 4. Execute the script.
-- ====================================================================================

/*
INSERT INTO elt_pipeline_configs (
    -- Core Pipeline Fields
    pipeline_name,          -- The asset group name in the Dagster UI (e.g., 'Sales').    
    import_name,            -- A unique identifier for this data source (e.g., 'daily_sales_csv'). MUST BE UNIQUE.
    file_pattern,           -- Pattern of the source file (e.g., 'sales_*.csv'). For scrapers, can be a dummy value.
    monitored_directory,    -- (Optional) Absolute path to the folder to watch for files (e.g., 'C:\\Pipelines\\Incoming'). NULL for manual/scheduled runs.
    connection_string,      -- (Optional) A specific database connection string. If NULL, the default resource is used.
    file_type,              -- The generic parser to use ('csv', 'psv', 'excel'). For custom parsers, use a descriptive name like 'custom_report'.
    staging_table,          -- The name of the SQL staging table (e.g., 'stg_daily_sales').
    column_mapping,         -- (Optional) JSON string for column renaming, e.g., '{"SourceCol": "StagingCol"}'. Can be auto-generated by the utility asset.
    destination_table,      -- The name of the final destination table (e.g., 'fact_sales').
    parser_function,        -- (Optional) Name of a custom function in custom_parsers.py (e.g., 'generic_selenium_scraper'). If NULL, uses `file_type`.
    scraper_config,         -- (Optional) JSON configuration for web/SFTP/configurable parsers. Use single quotes for the entire JSON string.
    transform_procedure,    -- The name of the SQL stored procedure for transformation (e.g., 'sp_transform_sales').
    load_method,            -- 'replace' (full refresh) or 'append' (incremental load).
    deduplication_key,      -- (Optional) For 'append' mode, comma-separated columns for deduplication (e.g., 'ID,Date').
    is_active,              -- 1 for active, 0 for disabled.
) VALUES (
    -- Core Pipeline Values
    'MyNewPipeline',                                -- pipeline_name
    'my_new_import',                                -- import_name
    'new_data_*.csv',                               -- file_pattern
    'C:\\data\\new_source',                         -- monitored_directory
    NULL,                                           -- connection_string
    'csv',                                          -- file_type
    'stg_my_new_data',                              -- staging_table
    NULL,                                           -- column_mapping
    'dest_my_new_data',                             -- destination_table
    NULL,                                           -- parser_function
    NULL,                                           -- scraper_config
    'sp_transform_my_new_data',                     -- transform_procedure
    'replace',                                      -- load_method
    NULL,                                           -- deduplication_key
    1,                                              -- is_active
);
*/

-- ====================================================================================
-- TEMPLATE 2: UPDATE an existing pipeline configuration
--
-- Instructions:
-- 1. Uncomment the UPDATE statement below.
-- 2. Set the new value for the field you want to change.
-- 3. Use the WHERE clause to target the correct pipeline by its `import_name`.
-- ====================================================================================

/*
UPDATE elt_pipeline_configs
SET
    monitored_directory = 'C:\\data\\new_location', -- Example: Change the monitored directory
    is_active = 0                                  -- Example: Disable the pipeline
WHERE
    import_name = 'my_new_import';                 -- Specify which pipeline to update
*/


-- ====================================================================================
-- TEMPLATE 3: DELETE a pipeline configuration
--
-- Instructions:
-- Use this with caution. Deleting a configuration will remove it from Dagster.
-- It's often safer to set `is_active = 0` using the UPDATE template.
-- ====================================================================================

/*
DELETE FROM elt_pipeline_configs
WHERE import_name = 'my_new_import'; -- Specify which pipeline to delete
*/